[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "outer"]
set = true

[templates.hypr]
input_path = './templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.waybar]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.wofi]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/wofi/colors.css'
[templates.swaync]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -R -rs'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/templates/reload-gtk.sh'
